### ISSUE TITLE
Unable to compile with MSVC 19.11 (VS15.3 or VS2017.3)

### ISSUE THREAD

**Issue by egorpugin** [rbock/sqlpp11#181]
Hi!

MS released VS 15.3 (2017.3) with first toolset update and build is broken in `/std:c++17` mode.
Errors:
```
\include\sqlpp11/statement.h(156): error C2903: '_base_t': symbol is neither a class template nor a function template
\include\sqlpp11/insert.h(109): note: see reference to class template instantiation 'sqlpp::statement_t<void,sqlpp::insert_t,sqlpp::no_into_t,sqlpp::no_insert_value_list_t>' being compiled
\date.h(111): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled
\include\sqlpp11/statement.h(166): error C3546: '...': there are no parameter packs available to expand
\include\sqlpp11/statement.h(173): error C3546: '...': there are no parameter packs available to expand
\include\sqlpp11/statement.h(179): error C3546: '...': there are no parameter packs available to expand
\include\sqlpp11/table.h(48): error C2903: '_member_t': symbol is neither a class template nor a function template
\include\sqlpp11/verbatim_table.h(53): note: see reference to class template instantiation 'sqlpp::table_t<sqlpp::verbatim_table_t,sqlpp::detail::unusable_pseudo_column_t>' being compiled
```

sqlite3 connector 0.24 + sqlpp11 develop.

**Comment by rbock** [comment]
Hi Egor,

Are those all error messages? No static assert or anything? Can you send a minimal example that produces this or a similar error?

Thanks,

Roland

**Comment by egorpugin** [comment]
Sure. :) And yes, no other static asserts or something.

```
#include <sqlpp11/sqlpp11.h>

int main()
{
    return 0;
}
```

**Comment by rbock** [comment]
Oh, wow!

That's scary... Does it also happen if you turn off the explicit C++17 mode?

Also, can you try including sqlpp11/verbatim_table.h, only?

**Comment by egorpugin** [comment]
Oops. I've tried other modes (c++14, c++latest) and they're broken too (with my example above).

With single `sqlpp11/verbatim_table.h` include.

```
\sqlpp11/verbatim_table.h(42): error C2039: 'make_char_sequence': is not a member of 'sqlpp'
\sqlpp11/verbatim_table.h(33): note: see declaration of 'sqlpp'
\sqlpp11/verbatim_table.h(42): error C2061: syntax error: identifier 'make_char_sequence'
\sqlpp11/verbatim_table.h(42): error C2238: unexpected token(s) preceding ';'
\sqlpp11/table.h(48): error C2903: '_member_t': symbol is neither a class template nor a function template
\sqlpp11/verbatim_table.h(53): note: see reference to class template instantiation 'sqlpp::table_t<sqlpp::verbatim_table_t,sqlpp::detail::unusable_pseudo_column_t>' being compiled
\sqlpp11/verbatim_table.h(59): error C2039: 'make_char_sequence': is not a member of 'sqlpp'
\sqlpp11/verbatim_table.h(33): note: see declaration of 'sqlpp'
\sqlpp11/verbatim_table.h(59): error C2061: syntax error: identifier 'make_char_sequence'
\sqlpp11/verbatim_table.h(59): error C2238: unexpected token(s) preceding ';'
```

**Comment by rbock** [comment]
Oh, ok, that is an actual error (missing include). Fixed it on develop.

Can you pull and try again?

Thanks!

**Comment by egorpugin** [comment]
With single `verbatim_table.h`:
```
\include\sqlpp11/table.h(48): error C2903: '_member_t': symbol is neither a class template nor a function template
\include\sqlpp11/verbatim_table.h(54): note: see reference to class template instantiation 'sqlpp::table_t<sqlpp::verbatim_table_t,sqlpp::detail::unusable_pseudo_column_t>' being compiled
```

**Comment by rbock** [comment]
Thanks! I am quite confident now that this is a compiler bug.
If you look at table.h and verbatim_table.h, you'll quickly spot the relevant parts:

```
  namespace detail
  {
    struct unusable_pseudo_column_t
    {
      struct _alias_t
      {
        template <typename T>
        struct _member_t // <---- This is the member template that the compiler cannot find
        {
        };
      };
      using _traits = make_traits<no_value_t>;
    };
  }
```

Above you see the `_member_t` template that the compiler cannot find here

```
  template <typename Table, typename... ColumnSpec>
  struct table_t : public table_base_t, public ColumnSpec::_alias_t::template _member_t<column_t<Table, ColumnSpec>>...
```

when specialized like this:

```
  struct verbatim_table_t : public table_t<verbatim_table_t, detail::unusable_pseudo_column_t>
  {
   //...
  };
```

I still need Microsoft's team to use sqlpp11 as a unit test :-(

It might be possible to create some alias template that wraps the `ColumnSpec::_alias_t::template _member_t` part. But there is a good chance that such a workaround will break older versions of MSVC.

So I do not have a good solution for this other than reporting a bug at Microsoft. Would you like to do that?

**Comment by rbock** [comment]
Does this compile on your machine?

```
template <typename Table, typename ColumnSpec>
struct column_t
{
};

struct table_base_t
{
};

template <typename Table, typename... ColumnSpec>
struct table_t : public table_base_t, public ColumnSpec::_alias_t::template _member_t<column_t<Table, ColumnSpec>>...
{
};

namespace detail
{
  struct unusable_pseudo_column_t
  {
    struct _alias_t
    {
      template <typename T>
      struct _member_t
      {
      };
    };
  };
}

struct verbatim_table_t : public table_t<verbatim_table_t, detail::unusable_pseudo_column_t>
{
};

int main()
{
}
```
That's basically the code that produced the error message (except that the struct bodies are more complex in the real code);

**Comment by egorpugin** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/3139514

**Comment by rbock** [comment]
Awesome!

**Comment by egorpugin** [comment]
New and correct link - https://developercommunity.visualstudio.com/content/problem/95983/c-vs152-153-regression-in-variadic-template-argume.html

**Comment by egorpugin** [comment]
According to https://connect.microsoft.com/VisualStudio/feedback/details/3139514
```
This issue has been fixed and will be available in the next major release of VS2017.
```
As I understand it will be in VS15.5.

**Comment by rbock** [comment]
That's good news indeed! Thanks again for reporting it.

I also talked to members of Microsoft's compiler team at CppCon. They are looking into adding sqlpp11 to their test suite. This would help a lot.

**Comment by rbock** [comment]
Hi,

I just learned that Microsoft regularly tests their compiler against all packages in https://github.com/Microsoft/vcpkg

As am not a Windows/MSVC user, it would be awesome if somebody could take the job of adding sqlpp11.

Best,

Roland

**Comment by Phantom190** [comment]
Hi guys, VS 15.5 preview is available now, and the snippet from egorpugin now compiles.
However, there's still 6 tests that won't compile (tried the branches 0.50, 0.51 and 0.52). I also tried the develop branch, and almost nothing compiles with that.

```

// count_of_count.cpp
2>X:\sqlpp11\include\sqlpp11/aggregate_functions/count.h(113): error C2338: count() cannot be used on an aggregate function
2>X:\sqlpp11\test_constraints\count_of_count.cpp(37): note: see reference to function template instantiation 'sqlpp::count_t<sqlpp::noop,sqlpp::count_t<sqlpp::noop,sqlpp::column_t<Table,test::TabBar_::Alpha>>> sqlpp::count<sqlpp::count_t<sqlpp::noop,sqlpp::column_t<Table,test::TabBar_::Alpha>>>(T)' being compiled
2>        with
2>        [
2>            Table=test::TabBar,
2>            T=sqlpp::count_t<sqlpp::noop,sqlpp::column_t<test::TabBar,test::TabBar_::Alpha>>
2>        ]
2>X:\date\date.h(132): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled

// max_of_max.cpp
1>X:\sqlpp11\include\sqlpp11/aggregate_functions/max.h(98): error C2338: max() cannot be used on an aggregate function
1>X:\sqlpp11\test_constraints\max_of_max.cpp(37): note: see reference to function template instantiation 'sqlpp::max_t<sqlpp::max_t<sqlpp::column_t<Table,test::TabBar_::Alpha>>> sqlpp::max<sqlpp::max_t<sqlpp::column_t<Table,test::TabBar_::Alpha>>>(T)' being compiled
1>        with
1>        [
1>            Table=test::TabBar,
1>            T=sqlpp::max_t<sqlpp::column_t<test::TabBar,test::TabBar_::Alpha>>
1>        ]
1>X:\date\date.h(132): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled

// must_not_insert.cpp
1>X:\sqlpp11\include\sqlpp11/insert_value_list.h(147): error C2338: at least one assignment is prohibited by its column definition in set()
1>X:\sqlpp11\include\sqlpp11/insert_value_list.h(513): note: see reference to function template instantiation 'sqlpp::assert_insert_set_allowed_t::assert_insert_set_allowed_t<>(void)' being compiled
1>X:\sqlpp11\test_constraints\must_not_insert.cpp(37): note: see reference to function template instantiation 'sqlpp::assert_insert_set_allowed_t sqlpp::no_insert_value_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::insert_t,sqlpp::into_t<void,Table>,sqlpp::no_insert_value_list_t>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\sqlpp11\test_constraints\must_not_insert.cpp(37): note: see reference to function template instantiation 'sqlpp::assert_insert_set_allowed_t sqlpp::no_insert_value_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::insert_t,sqlpp::into_t<void,Table>,sqlpp::no_insert_value_list_t>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\date\date.h(132): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled

// must_not_update.cpp

1>X:\sqlpp11\include\sqlpp11/update_list.h(151): error C2338: at least one assignment is prohibited by its column definition in set()
1>X:\sqlpp11\include\sqlpp11/update_list.h(260): note: see reference to function template instantiation 'sqlpp::assert_update_set_allowed_t::assert_update_set_allowed_t<>(void)' being compiled
1>X:\sqlpp11\test_constraints\must_not_update.cpp(36): note: see reference to function template instantiation 'sqlpp::assert_update_set_allowed_t sqlpp::no_update_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::update_t,sqlpp::single_table_t<void,Table>,sqlpp::no_update_list_t,sqlpp::no_where_t<true>>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\sqlpp11\test_constraints\must_not_update.cpp(36): note: see reference to function template instantiation 'sqlpp::assert_update_set_allowed_t sqlpp::no_update_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::update_t,sqlpp::single_table_t<void,Table>,sqlpp::no_update_list_t,sqlpp::no_where_t<true>>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Alpha>,sqlpp::integral_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Gamma>,sqlpp::boolean_operand>,sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\date\date.h(132): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled

// no_conversion_operator_if_null_not_trivial.cpp

1>X:\sqlpp11\test_constraints\no_conversion_operator_if_null_not_trivial.cpp(45): error C2440: 'initializing': cannot convert from 'const sqlpp::result_field_t<Db,FieldSpec>' to 'int'
1>        with
1>        [
1>            Db=MockDbT<true>,
1>            FieldSpec=sqlpp::field_spec_t<test::TabBar_::Alpha::_alias_t,sqlpp::integral,true,false>
1>        ]
1>X:\sqlpp11\test_constraints\no_conversion_operator_if_null_not_trivial.cpp(45): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

// require_insert.cpp

1>X:\sqlpp11\include\sqlpp11/insert_value_list.h(153): error C2338: at least one required column is missing in set()
1>X:\sqlpp11\include\sqlpp11/insert_value_list.h(513): note: see reference to function template instantiation 'sqlpp::assert_insert_static_set_all_required_t::assert_insert_static_set_all_required_t<>(void)' being compiled
1>X:\sqlpp11\test_constraints\require_insert.cpp(37): note: see reference to function template instantiation 'sqlpp::assert_insert_static_set_all_required_t sqlpp::no_insert_value_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::insert_t,sqlpp::into_t<void,Table>,sqlpp::no_insert_value_list_t>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\sqlpp11\test_constraints\require_insert.cpp(37): note: see reference to function template instantiation 'sqlpp::assert_insert_static_set_all_required_t sqlpp::no_insert_value_list_t::_base_t<sqlpp::detail::statement_policies_t<Db,sqlpp::insert_t,sqlpp::into_t<void,Table>,sqlpp::no_insert_value_list_t>>::set<sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>>(sqlpp::assignment_t<sqlpp::column_t<Table,test::TabBar_::Beta>,sqlpp::text_operand>) const' being compiled
1>        with
1>        [
1>            Db=void,
1>            Table=test::TabBar
1>        ]
1>X:\date\date.h(132): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled
```

**Comment by rbock** [comment]
As @juandent commented here https://github.com/rbock/sqlpp11-connector-sqlite3/issues/36#issuecomment-348614085 , VS 15.5.0 Preview 5 seems to fix the problem. Keep your fingers crossed that the actual release will do so, too :-)

**Comment by rbock** [comment]
With current versions, it should be fine. Please open a new issue otherwise.
