### ISSUE TITLE
Compilation issue with table having "ref" named field

### ISSUE THREAD

**Issue by MatthieuTexier** [rbock/sqlpp11#345]
Hi Roland,
One the tables I work with has a field named "ref".
Because the tables structs inherit from table_t and table_t have a member fonction called ref, I have compilation error on
db(insert_into(my_table).set(my_table.ref = something))
How would you deal with that ?
Best regards,
Matthieu

**Comment by rbock** [comment]
I admit I had to go through the git history to get an idea what `ref` might have been used for? It seems to me that it is actually just there by accident. It was introduced in 73097e989f063871eb876a1aa15ede0a6e30860c and not used even then.

Feel free to remove with a pull request.

In unexpected case this causes any issues, it should be possible to introduce a free function as a replacement.
